version: '3'
services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo_discounts
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db_data_discount
    networks:
      - network

  backend:
    container_name: backend_discounts
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "9000:9000"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://root:root@mongo:27017
      - QUARKUS_MONGODB_DATABASE=discounts
    depends_on:
      - mongo
    networks:
      - network

networks:
  network: