name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          QUARKUS_MONGODB_CONNECTION_STRING: mongodb://localhost:27017
          QUARKUS_MONGODB_DATABASE: discounts

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean install -DskipTests=false

      - name: Run Tests
        run: mvn -B test
