name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          QUARKUS_MONGODB_CONNECTION_STRING: mongodb://localhost:27017
          QUARKUS_MONGODB_DATABASE: discounts

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean install -DskipTests=false

      - name: Run Tests
        run: mvn -B test

      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t jernejofic444/discount-service -f src/main/docker/Dockerfile.jvm .


      - name: Push Docker image
        run: docker push jernejofic444/discount-service
